# Generated by Django 4.2.1 on 2023-06-09 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('famFeed', '0002_tablon_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recuerdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('imagenRecuerdo', models.ImageField(null=True, upload_to='famFeedRecuerdos', verbose_name='imagenRecuerdo')),
                ('texto', models.CharField(max_length=1000)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('tablon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuerdos', to='famFeed.tablon')),
            ],
            options={
                'verbose_name': 'recuerdo',
                'verbose_name_plural': 'recuerdos',
            },
        ),
    ]
