# Generated by Django 4.2.1 on 2023-06-10 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('famFeed', '0003_recuerdo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.CharField(max_length=50)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('recuerdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='famFeed.tablon')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentario',
            },
        ),
    ]
